
[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[colors.cursor]
text = "#000000"
cursor = "#FFFFFF"

[colors.normal]
black = "#000000"
red = "#222222"
green = "#333333"
yellow = "#444444"
blue = "#555555"
magenta = "#666666"
cyan = "#777777"
white = "#DDDDDD"

[colors.bright]
black = "#4D4D4D"
red = "#666666"
green = "#777777"
yellow = "#888888"
blue = "#999999"
magenta = "#AAAAAA"
cyan = "#BBBBBB"
white = "#FFFFFF"

[colors.selection]
text = "#FFFFFF"
background = "#333333"
